services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9006:3001
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
